# Generated by Django 4.1.9 on 2023-06-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="date_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
